### PR TITLE
enforce python3 and properly parse ike-scan output

### PR DESCRIPTION
**Pull request by zOrg1331**
This fixes issue #13 in Zamanry/iker repo

### CODE REVIEW

**Comment by Zamanry** [comment]
Has this been tested? Was the problem in #13 due to the UTF-8 encoding hence the move to IO?

**Comment by zOrg1331** [comment]
I used this and other changes provided in the recent pull requests quite intensively and they worked. I can't say that it was *tested* as I did not write any specific tests for that.

**Comment by Zamanry** [comment]
I am gonna work on getting your pull requests merged and tested this week.

In regards to Python versions, I am going to move forward not supporting Python 2.X anymore in iker. I plan to update the README with stating only Python 3.10+ is supported once I get a chance to test your updates. I am willing to change the shebang to `#!/usr/bin/env python` as to let the user specify their environment version, which I typically add in all my Python scripts. Hopefully this a decent compromise.

**Comment by zOrg1331** [comment]
See the pull request #22.

**Pull request closed without merging**
